name: DSM Rollback Deployment Test.

on:
  workflow_dispatch:
    inputs:
      backend_version:
        description: 'Backend image tag'
        required: true
      frontend_version:
        description: 'Frontend image tag'
        required: true

env:
  AWS_REGION: ap-south-1
  ECR_REPO_BACKEND: dsm-test-repo
  ECR_REPO_FRONTEND: dsm-test-fe-repo
  ECR_REGISTRY: 687444329037.dkr.ecr.ap-south-1.amazonaws.com

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Rollback selected services on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_TEST }}
          username: ${{ secrets.SERVER_USER_TEST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: ECR_REPO_BACKEND,ECR_REPO_FRONTEND,ECR_REGISTRY,AWS_REGION
          script: |
            BACKEND_IMAGE_TAG="${{ github.event.inputs.backend_version }}"
            FRONTEND_IMAGE_TAG="${{ github.event.inputs.frontend_version }}"

            echo "Logging into ECR..."
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

            cd /home/ntkyc/workspace/dsm-mono-test/dsm-mono
            git checkout cicd_test && git pull

            echo "Pulling backend image: $BACKEND_IMAGE_TAG"
            docker pull $ECR_REGISTRY/$ECR_REPO_BACKEND:$BACKEND_IMAGE_TAG

            echo "Pulling frontend image: $FRONTEND_IMAGE_TAG"
            docker pull $ECR_REGISTRY/$ECR_REPO_FRONTEND:$FRONTEND_IMAGE_TAG

            echo "Updating compose file with target tags..."
            sed -i "s|$ECR_REPO_BACKEND:.*|$ECR_REPO_BACKEND:$BACKEND_IMAGE_TAG|g" docker-compose-dev.yml
            sed -i "s|$ECR_REPO_FRONTEND:.*|$ECR_REPO_FRONTEND:$FRONTEND_IMAGE_TAG|g" docker-compose-dev.yml

            echo "Starting containers with specified image tags..."
            docker compose -f docker-compose-dev.yml up -d --force-recreate
